language: java
jdk: 
   - oraclejdk8
addons:
   sonarqube:
      token:
          secure: $SONAR_TOKEN

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: shielded-beyond-76020

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
